# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 20:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='粉丝名')),
                ('tel', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[35678]\\d{9}')], verbose_name='用户号码')),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='用户密码')),
                ('status', models.SmallIntegerField(choices=[(1, '不能留言'), (2, '不能登录'), (3, '正常')], default=3, verbose_name='状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('head', models.ImageField(default='head/icon4.png', upload_to='fans/%Y%m', verbose_name='用户头像')),
                ('score', models.IntegerField(default=1000, verbose_name='积分')),
            ],
            options={
                'verbose_name': '粉丝管理',
                'verbose_name_plural': '粉丝管理',
                'db_table': 'Buser',
            },
        ),
    ]
