# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buser',
            name='score',
            field=models.IntegerField(default=6666, verbose_name='积分'),
        ),
    ]
