# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0002_auto_20190214_2109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buser',
            table='Buserhghgyuu',
        ),
    ]
