# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liuyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('context', models.TextField(max_length=200, verbose_name='留言内容')),
                ('user_tel', models.CharField(max_length=20, verbose_name='用户手机号')),
                ('content_id', models.CharField(max_length=10, verbose_name='文章ID')),
                ('parent_id', models.SmallIntegerField(choices=[(1, '回复'), (2, '留言')], default=2)),
            ],
            options={
                'verbose_name': '留言管理',
                'verbose_name_plural': '留言管理',
                'db_table': 'Bconment',
            },
        ),
    ]
