# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_liuyan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Bcomment',
        ),
    ]
