# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_liuyan', '0002_auto_20190215_2249'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
