# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('img_url', models.ImageField(upload_to='goods_gallery/%Y%m/%d', verbose_name='相册图片地址')),
            ],
            options={
                'verbose_name': '商品相册管理',
                'verbose_name_plural': '商品相册管理',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku_name', models.CharField(max_length=50, verbose_name='SKU')),
                ('brief', models.TextField(verbose_name='SKU简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='价格')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('stock', models.IntegerField(verbose_name='库存')),
                ('sales_val', models.IntegerField(verbose_name='销量')),
                ('logo', models.ImageField(upload_to='goods/%Y%m/%d', verbose_name='封面图片')),
                ('is_on_sale', models.BooleanField(choices=[(False, '下架'), (True, '上架')], default=False, verbose_name='是否上架')),
                ('goods_spu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSKU', verbose_name='商品SPU_id')),
            ],
            options={
                'verbose_name': '商品SKU表管理',
                'verbose_name_plural': '商品SKU表管理',
                'db_table': 'goodssku',
            },
        ),
        migrations.CreateModel(
            name='GoodsSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spu_name', models.CharField(max_length=50, verbose_name='SPU名')),
                ('spu_detail', models.TextField(verbose_name='SPU简介')),
            ],
            options={
                'verbose_name': '商品SPU表管理',
                'verbose_name_plural': '商品SPU表管理',
                'db_table': 'goodsspu',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type_name', models.CharField(max_length=50, verbose_name='商品类名')),
                ('sort_detail', models.TextField(verbose_name='分类详情')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '商品类型表管理',
                'verbose_name_plural': '商品类型表管理',
                'db_table': 'goodstype',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('unit_name', models.CharField(max_length=50, verbose_name='单位名')),
            ],
            options={
                'verbose_name': '单位表管理',
                'verbose_name_plural': '单位表管理',
                'db_table': 'unit',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='goods_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsType', verbose_name='商品分类id'),
        ),
        migrations.AddField(
            model_name='goodsphoto',
            name='goods_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSKU', verbose_name='商品SKU'),
        ),
    ]
