# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodssku',
            old_name='goods_spu_id',
            new_name='goods_spu',
        ),
        migrations.RenameField(
            model_name='goodssku',
            old_name='goods_type_id',
            new_name='goods_type',
        ),
    ]
