# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20190123_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsphoto',
            old_name='goods_sku_id',
            new_name='goods_sku',
        ),
    ]
