# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20190123_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('act_name', models.CharField(max_length=50, verbose_name='活动名')),
                ('img_url', models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='活动图片地址')),
                ('url_address', models.URLField(verbose_name='活动的url地址')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Activity_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='活动专区名称')),
                ('describe', models.TextField(verbose_name='专区的描述')),
                ('is_on_sale', models.BooleanField(choices=[(False, '下架'), (True, '上架')], default=False, verbose_name='是否上架')),
                ('goods_sku', models.ManyToManyField(to='commodity.GoodsSKU', verbose_name='商品')),
            ],
            options={
                'verbose_name': '活动专区管理',
                'verbose_name_plural': '活动专区管理',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='轮播活动名')),
                ('img_url', models.ImageField(upload_to='carousel/%Y%m/%d', verbose_name='轮播图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSKU', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '轮播管理',
                'verbose_name_plural': '轮播管理',
            },
        ),
    ]
