# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_activity_activity_area_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.GoodsSPU', verbose_name='商品SPU_id'),
        ),
    ]
