# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 20:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20190123_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspu',
            name='spu_detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='SPU简介'),
        ),
    ]
