# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='logo',
            field=models.ImageField(default='default/shop1.png', upload_to='shop/%Y%m/%d', verbose_name='店铺LOGO'),
        ),
    ]
