# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='users',
            name='logo',
            field=models.ImageField(default='head/memtx.png', upload_to='shop/%Y%m/%d', verbose_name='店铺LOGO'),
        ),
    ]
